; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = waterius_2 ; esp01_1m ; waterius_2
test_dir = test
extra_configs = secrets.ini

; fix SCons 4.7.0 FortranCommon bug
platform_packages = platformio/tool-scons@~4.40801.0

[env]
firmware_version = "\"2.0.36\""

[libraries]
arduinojson = ArduinoJson@7.3.1
pubsubclient = PubSubClient@2.8.0
espasyncwebserver = ESP32Async/ESPAsyncWebServer@3.6.0
asynctcp = ESP32Async/ESPAsyncTCP@2.0.0

[env:esp01_1m]
extra_scripts = post:post_compile.py
board = esp01_1m
upload_port = /dev/cu.usbserial-2130 ;/dev/cu.usbserial-2120
upload_speed = 115200
board_upload.resetmethod = nodemcu
board_build.f_cpu = 80000000L
board_build.flash_mode = qio
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.1m256.ld
monitor_filters = esp8266_exception_decoder
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-2120 ; /dev/cu.usbserial-2130
platform = espressif8266@4.2.1
framework = arduino
lib_deps = 
	${libraries.pubsubclient}
	${libraries.arduinojson}
	${libraries.espasyncwebserver}
	${libraries.asynctcp}
build_flags = 
	-DFIRMWARE_VERSION=${this.firmware_version}
	-DWATERIUS_MODEL=0
	-DLOG_FREE_HEAP
	-DLOG_LEVEL_INFO
platform_packages = platformio/tool-scons@~4.40801.0


[env:waterius_2]
extra_scripts = post:post_compile.py
board = nodemcuv2
upload_port = /dev/cu.usbserial-2130  ;/dev/cu.usbserial-0001
upload_speed = 460800
board_build.f_cpu = 80000000L
board_build.flash_mode = qio
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m1m.ld
monitor_port = /dev/cu.usbserial-2120
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
platform = espressif8266@4.2.1
framework = arduino
lib_deps = 
	${libraries.pubsubclient}
	${libraries.arduinojson}
	${libraries.espasyncwebserver}
	${libraries.asynctcp}
build_flags = 
	-DFIRMWARE_VERSION=${this.firmware_version}
	-DWATERIUS_MODEL=2
	-DLOG_FREE_HEAP
	-DLOG_LEVEL_INFO
platform_packages = platformio/tool-scons@~4.40801.0


[env:nodemcuv2]
# только для отладки на столе на nodemcu плате
board = nodemcuv2
upload_port = /dev/cu.usbserial-0001
upload_speed = 921800
board_build.f_cpu = 80000000L
board_build.flash_mode = qio
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.1m256.ld
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-2130
platform = espressif8266@4.1.0
framework = arduino
lib_deps = 
	${libraries.pubsubclient}
	${libraries.arduinojson}
	${libraries.espasyncwebserver}
	${libraries.asynctcp}
build_flags = 
	-DFIRMWARE_VERSION=${this.firmware_version}
	-DLOG_FREE_HEAP
	-DLOG_LEVEL_INFO
	-DWM_DEBUG_LEVEL=DEBUG_MAX
	-DDEBUG_ESP_WIFI
	-DDEBUG_ESP_CORE
platform_packages = platformio/tool-scons@~4.40801.0


[env:native]
platform = native
test_framework = googletest
build_flags = -std=c++17
lib_deps = ArduinoJson@7.3.1
test_filter = test_ota/*
platform_packages = platformio/tool-scons@~4.40801.0

[secrets]
wifi_ssid = 
wifi_password = 
waterius_email = 
mqtt_host = 
mqtt_username = 
mqtt_password = 
blynk_key =
